//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPR.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class Bindings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Bindings defaultInstance = ((Bindings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Bindings())));
        
        public static Bindings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Escape")]
        public global::PPR.Properties.InputKey back {
            get {
                return ((global::PPR.Properties.InputKey)(this["back"]));
            }
            set {
                this["back"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Backspace")]
        public global::PPR.Properties.InputKey erase {
            get {
                return ((global::PPR.Properties.InputKey)(this["erase"]));
            }
            set {
                this["erase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Up")]
        public global::PPR.Properties.InputKey speedUp {
            get {
                return ((global::PPR.Properties.InputKey)(this["speedUp"]));
            }
            set {
                this["speedUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Down")]
        public global::PPR.Properties.InputKey speedDown {
            get {
                return ((global::PPR.Properties.InputKey)(this["speedDown"]));
            }
            set {
                this["speedDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Right")]
        public global::PPR.Properties.InputKey hpDrainUp {
            get {
                return ((global::PPR.Properties.InputKey)(this["hpDrainUp"]));
            }
            set {
                this["hpDrainUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Left")]
        public global::PPR.Properties.InputKey hpDrainDown {
            get {
                return ((global::PPR.Properties.InputKey)(this["hpDrainDown"]));
            }
            set {
                this["hpDrainDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LShift+Right,RShift+Right")]
        public global::PPR.Properties.InputKey hpRestorageUp {
            get {
                return ((global::PPR.Properties.InputKey)(this["hpRestorageUp"]));
            }
            set {
                this["hpRestorageUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LShift+Left,RShift+Left")]
        public global::PPR.Properties.InputKey hpRestorageDown {
            get {
                return ((global::PPR.Properties.InputKey)(this["hpRestorageDown"]));
            }
            set {
                this["hpRestorageDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LAlt+Up,RAlt+Up")]
        public global::PPR.Properties.InputKey linesFrequencyUp {
            get {
                return ((global::PPR.Properties.InputKey)(this["linesFrequencyUp"]));
            }
            set {
                this["linesFrequencyUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LAlt+Down,RAlt+Down")]
        public global::PPR.Properties.InputKey linesFrequencyDown {
            get {
                return ((global::PPR.Properties.InputKey)(this["linesFrequencyDown"]));
            }
            set {
                this["linesFrequencyDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F2")]
        public global::PPR.Properties.InputKey initialOffsetUp {
            get {
                return ((global::PPR.Properties.InputKey)(this["initialOffsetUp"]));
            }
            set {
                this["initialOffsetUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F1")]
        public global::PPR.Properties.InputKey initialOffsetDown {
            get {
                return ((global::PPR.Properties.InputKey)(this["initialOffsetDown"]));
            }
            set {
                this["initialOffsetDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LShift+F2,RShift+F2")]
        public global::PPR.Properties.InputKey initialOffsetUpBoost {
            get {
                return ((global::PPR.Properties.InputKey)(this["initialOffsetUpBoost"]));
            }
            set {
                this["initialOffsetUpBoost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LShift+F1,RShift+F1")]
        public global::PPR.Properties.InputKey initialOffsetDownBoost {
            get {
                return ((global::PPR.Properties.InputKey)(this["initialOffsetDownBoost"]));
            }
            set {
                this["initialOffsetDownBoost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LShift+Up,RShift+Up")]
        public global::PPR.Properties.InputKey speedUpSlow {
            get {
                return ((global::PPR.Properties.InputKey)(this["speedUpSlow"]));
            }
            set {
                this["speedUpSlow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LShift+Down,RShift+Down")]
        public global::PPR.Properties.InputKey speedDownSlow {
            get {
                return ((global::PPR.Properties.InputKey)(this["speedDownSlow"]));
            }
            set {
                this["speedDownSlow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PageUp")]
        public global::PPR.Properties.InputKey fastScrollUp {
            get {
                return ((global::PPR.Properties.InputKey)(this["fastScrollUp"]));
            }
            set {
                this["fastScrollUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PageDown")]
        public global::PPR.Properties.InputKey fastScrollDown {
            get {
                return ((global::PPR.Properties.InputKey)(this["fastScrollDown"]));
            }
            set {
                this["fastScrollDown"] = value;
            }
        }
    }
}
